export {
  PerpsClient,
  PerpsHttpError,
  PerpsServiceUnavailableError,
} from './client'
export type {
  GenericResponse,
  ErrorResponse,
  StatusResult,
  LoginGetChallengeRequest,
  LoginChallengeResult,
  LoginCompleteChallengeRequest,
  LoginCompleteChallengeResult,
  AgreementRequest,
  TradingPair,
  MarketsResult,
  TokenConfig,
  Sparkline,
  Contract,
  HistoryResult,
  AccountWalletKey,
  DepositAddressListRequest,
  DepositAddress,
  ProvisionAddressRequest,
  ProvisionAddressResult,
  AccountInfo,
  PortfolioSummary,
  PortfolioGraphPoint,
  PerpsBalance,
  AddressBookEntry,
  AddressBookResult,
  AddressBookGetChallengeRequest,
  AddressBookCompleteChallengeRequest,
  WithdrawRequest,
  WithdrawResult,
  CreateOrderRequest,
  OrderResult,
  Position,
  LeverageSetting,
  MarkPrice,
  MaxOrderSizeLevel,
  MaxOrderSizeResult,
  PageInfo,
  PaginatedResponse,
  ApiOrder,
  ApiFill,
  WalletDeposit,
  WalletWithdrawal,
} from './types'

export type {
  WsPublicChannel,
  WsPrivateChannel,
  WsChannel,
  WsOutboundOp,
  WsOutboundFrame,
  WsInboundType,
  WsInboundFrame,
  WsConnectionState,
  WsAuthStatus,
  WsFrameHandler,
} from './wsTypes'

export { perpsWs, createPerpsWs } from './ws'
export type { PerpsWs, PerpsWsOptions } from './ws'
