steps:
  # Copy the latest ABI
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -m
      - cp
      - gs://reef-abis/master/AbtsRequestWithoutReef.json
      - ./app/scripts/coralConfig/

  # Install dependencies per package.json
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - install

  # Build the dist
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - run
      - build

  # Deploy to the bucket
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -m
      - cp
      - -r
      - ./dist/*
      - gs://mew-staging.heycoral.com
timeout: 1800s
options:
  machineType: 'N1_HIGHCPU_32'
