module.exports = [
  'https://localhost:8080',
  'wss://localhost:8080',
  'https://192.168.1.9:8080',
  'wss://192.168.1.9:8080',
  'https://swap.mewapi.io:443',
  'wss://api.thegraph.com/subgraphs/name/aave/',
  'https://api.thegraph.com:443/subgraphs/name/aave/',
  'wss://connect.mewapi.io:443',
  'wss://connect2.mewapi.io:443',
  'https://protocol-api.aave.com:443',
  'wss://bridge.walletconnect.org:443',
  'http://localhost:8178',
  'ws://127.0.0.1:8178',
  'https://unstoppabledomains.com:443',
  'https://o382951.ingest.sentry.io:443',
  'https://s3.us-west-2.amazonaws.com:443/mew-ipfs-bucket',
  'wss://www.walletlink.org:443',
  'https://estimategas.mewapi.io:443',
  'https://api.ethvm.com:443',
  'wss://apiws.ethvm.com:443',
  'https://nft.mewapi.io:443',
  'https://staked.mewapi.io:443',
  'https://stakedtest.mewapi.io:443',
  'https://tx.info.aquacha.in:443/api', // aqua
  'https://rpc.xdaichain.com:443',
  'https://myetherwallet.matomo.cloud:443',
  'https://qa.mewwallet.dev:443',
  'https://mainnet.mewwallet.dev:443',
  'https://staging.mewwallet.dev:443',
  'https://development.mewwallet.dev:443',
  'https://tokenbalance.mewapi.io:443',
  'https://requestcache.mewapi.io:443',
  'https://api.thegraph.com:443/subgraphs/name/ensdomains/',
  'https://api.wallet.coinbase.com:443',
  'data:',
  'https://registry.walletconnect.org:443',
  'https://cdn.live.ledger.com:443',
  'https://app.lokalise.com:443',
  'https://registry.walletconnect.org:443/data/wallets.json',
  'wss://*.bridge.walletconnect.org:443',
  // intercom stuff
  'api-iam.intercom.io:443',
  'https://api.zilliqa.com:443',
  'https://widget.intercom.io:443',
  'https://api-iam.intercom.io:443',
  'https://js.intercomcdn.com:443',
  'wss://nexus-websocket-a.intercom.io:443',
  'https://js.intercomcdn.com:443',
  'https://uploads.intercomcdn.com:443',
  // Nodes
  'https://nodes.mewapi.io:443',
  'wss://nodes.mewapi.io:443',
  'wss://www.ethercluster.com:443',
  'wss://rpc.gochain.io:443/ws',
  'https://mainnet.infura.io:443',
  // Dapps
  'https://ethblocksapi.mewapi.io:443' //Eth Blocks
];
