import { NetworkNames } from '@enkryptcom/types'

const chainToEnum: Record<string, NetworkNames> = {
  BITCOIN: NetworkNames.Bitcoin,
  BITCOIN_TEST: NetworkNames.BitcoinTest,
  DOGECOIN: NetworkNames.Dogecoin,
  LITECOIN: NetworkNames.Litecoin,
  ARBITRUM: NetworkNames.Arbitrum,
  ARBITRUM_NOVA: NetworkNames.ArbitrumNova,
  ARTHERA: NetworkNames.Arthera,
  ARTHERA_TEST: NetworkNames.ArtheraTest,
  ASTAR_EVM: NetworkNames.AstarEVM,
  AURORA: NetworkNames.Aurora,
  AVALANCHE: NetworkNames.Avalanche,
  BASE: NetworkNames.Base,
  BLAST: NetworkNames.Blast,
  BSC: NetworkNames.Binance,
  CAGA_ANKARA: NetworkNames.CagaAnkara,
  CANTO: NetworkNames.Canto,
  CELO: NetworkNames.Celo,
  COTI_DEVNET: NetworkNames.CotiDevnet,
  DEGEN: NetworkNames.Degen,
  EDGEWARE_EVM: NetworkNames.EdgeEVM,
  ETHEREUM: NetworkNames.Ethereum,
  ETHEREUM_CLASSIC: NetworkNames.EthereumClassic,
  ETHEREUM_HOLESKY: NetworkNames.Holesky,
  ETHEREUM_SEPOLIA: NetworkNames.Sepolia,
  FANTOM: NetworkNames.Fantom,
  // FIRE: NetworkNames.Fire,
  // FORM: NetworkNames.Form,
  FORM_TESTNET: NetworkNames.FormTestnet,
  FORMA: NetworkNames.Forma,
  // FRAXTAL: NetworkNames.Fraxtal,
  GNOSIS: NetworkNames.Gnosis,
  GODWOKEN: NetworkNames.Godwoken,
  HAM: NetworkNames.Ham,
  IMMUTABLE_ZKEVM: NetworkNames.ImmutableZkevm,
  // KAIA: NetworkNames.Kai,
  KARURA_EVM: NetworkNames.KaruraEVM,
  LINEA: NetworkNames.Linea,
  MANTA_PACIFIC: NetworkNames.MantaPacific,
  MODE: NetworkNames.Mode,
  MOONBEAM: NetworkNames.Moonbeam,
  MOONRIVER: NetworkNames.Moonriver,
  OKT_CHAIN: NetworkNames.Okc,
  ONTOLOGY_EVM: NetworkNames.OntologyEVM,
  OP_BNB: NetworkNames.OpBNB,
  OPTIMISTIC_ETHEREUM: NetworkNames.Optimism,
  PALM: NetworkNames.Palm,
  POLYGON: NetworkNames.Matic,
  POLYGON_ZKEVM: NetworkNames.MaticZK,
  PROOF_OF_PLAY_APEX: NetworkNames.ProofOfPlayApex,
  PUPPY_NET: NetworkNames.PuppyNet,
  RARI: NetworkNames.Rari,
  ROLLUX: NetworkNames.Rollux,
  ROLLUX_TEST: NetworkNames.RolluxTest,
  ROOTSTOCK: NetworkNames.Rootstock,
  ROOTSTOCK_TESTNET: NetworkNames.RootstockTestnet,
  SANKO: NetworkNames.Sanko,
  SCROLL: NetworkNames.Scroll,
  SHIDEN_EVM: NetworkNames.ShidenEVM,
  SHIBARIUM: NetworkNames.Shibarium,
  SKALE_BLOCK_BRAWLERS: NetworkNames.SkaleBlockBrawlers,
  SKALE_CALYPSO: NetworkNames.SkaleCalypso,
  SKALE_CHAOS: NetworkNames.SkaleChaos,
  SKALE_CRYPTO_BLADES: NetworkNames.SkaleCryptoBlades,
  SKALE_CRYPTO_COLOSSEUM: NetworkNames.SkaleCryptoColosseum,
  SKALE_EUROPA: NetworkNames.SkaleEuropa,
  SKALE_EXORDE: NetworkNames.SkaleExorde,
  SKALE_NEBULA: NetworkNames.SkaleNebula,
  SKALE_RAZOR: NetworkNames.SkaleRazor,
  SKALE_TITAN: NetworkNames.SkaleTitan,
  SYSCOIN_NEVM: NetworkNames.Syscoin,
  SYSCOIN_NEVM_TEST: NetworkNames.SyscoinTest,
  TELOS: NetworkNames.Telos,
  X_LAYER: NetworkNames.XLayer,
  Z_CHAINS: NetworkNames.ZChains,
  ZKSYNC: NetworkNames.ZkSync,
  ZKSYNC_GOERLI: NetworkNames.ZkSyncGoerli,
  KADENA: NetworkNames.Kadena,
  KADENA_TESTNET: NetworkNames.KadenaTestnet,
  ACALA: NetworkNames.Acala,
  AMPLITUDE: NetworkNames.Amplitude,
  ASSET_HUB_DOT: NetworkNames.AssetHubDOT,
  ASSET_HUB_KSM: NetworkNames.AssetHubKSM,
  ASTAR: NetworkNames.Astar,
  BIFROST: NetworkNames.Bifrost,
  BITFROST_KUSAMA: NetworkNames.BifrostKusama,
  EDGEWARE: NetworkNames.Edgeware,
  KARURA: NetworkNames.Karura,
  KUSAMA: NetworkNames.Kusama,
  OPAL: NetworkNames.Opal,
  PENDULUM: NetworkNames.Pendulum,
  POLKADOT: NetworkNames.Polkadot,
  QUARTZ: NetworkNames.Quartz,
  SHIDEN: NetworkNames.Shiden,
  UNIQUE: NetworkNames.Unique,
  VARA: NetworkNames.Vara,
  WESTEND: NetworkNames.Westend,
  SOLANA: NetworkNames.Solana
};

export { chainToEnum }