const AddressEventType = {
  NEW_ERC20_TRANSFER: 'NEW_ERC20_TRANSFER',
  NEW_ERC721_TRANSFER: 'NEW_ERC721_TRANSFER',
  NEW_ETH_TRANSFER: 'NEW_ETH_TRANSFER',
  NEW_MINED_BLOCK: 'NEW_MINED_BLOCK',
  NEW_MINED_UNCLE: 'NEW_MINED_UNCLE'
};

export { AddressEventType };
