export default {
  landingPage: 'LP',
  header: 'Header',
  footer: 'Footer',
  dashboard: 'Dashboard',
  connectionType: 'connectionType',
  createWallet: 'CW',
  accessWallet: 'AW',
  buyHardware: 'BH',
  exitDashboard: 'exitDashboard',
  networkSwitch: 'networkSwitch',
  gasSwitch: 'gasSwitch',
  swap: 'swapFlow',
  swapAmplitude: 'Swap',
  dapp: 'dapp',
  swapTokenPair: 'swapTokenPair',
  swapToken: 'swapToken',
  globalError: 'globalError',
  enkrypt: 'enkrypt',
  mewwallet: 'mewwallet',
  buySell: 'buySell',
  mewVersion: 'mewVersion'
};
