export default {
  landingPage: 'LP',
  header: 'Header',
  footer: 'Footer',
  dashboard: 'Dasboard',
  connectionType: 'connectionType',
  createWallet: 'createWallet',
  accessWallet: 'accessWallet',
  exitDashboard: 'exitDashboard',
  networkSwitch: 'networkSwitch',
  gasSwitch: 'gasSwitch',
  swap: 'swapFlow',
  swapAmplitude: 'Swap',
  dapp: 'dapp',
  swapTokenPair: 'swapTokenPair',
  swapToken: 'swapToken',
  globalError: 'globalError',
  enkrypt: 'enkrypt',
  mewwallet: 'mewwallet',
  buySell: 'buySell',
  mewVersion: 'mewVersion'
};
