const ChangellyCurrencies = {
  ABYSS: { symbol: 'ABYSS', name: 'The Abyss' },
  ADX: { symbol: 'ADX', name: 'AdEx' },
  AE: { symbol: 'AE', name: 'Aeternity' },
  ANT: { symbol: 'ANT', name: 'Aragon' },
  ARN: { symbol: 'ARN', name: 'Aeron' },
  BAT: { symbol: 'BAT', name: 'Basic Attention Token' },
  BETR: { symbol: 'BETR', name: 'BetterBetting' },
  BKX: { symbol: 'BKX', name: 'Bankex' },
  BNB: { symbol: 'BNB', name: 'Binance token' },
  BNT: { symbol: 'BNT', name: 'Bancor Network Token' },
  BRD: { symbol: 'BRD', name: 'Bread' },
  CVC: { symbol: 'CVC', name: 'Civic' },
  DAI: { symbol: 'DAI', name: 'Dai' },
  DCN: { symbol: 'DCN', name: 'Dentacoin' },
  DENT: { symbol: 'DENT', name: 'Dent' },
  DGD: { symbol: 'DGD', name: 'DigixDAO' },
  DGTX: { symbol: 'DGTX', name: 'Digitex Futures' },
  DNT: { symbol: 'DNT', name: 'district0x' },
  EDG: { symbol: 'EDG', name: 'Edgeless' },
  ENJ: { symbol: 'ENJ', name: 'Enjin' },
  ETH: { symbol: 'ETH', name: 'Ethereum' },
  EURS: { symbol: 'EURS', name: 'STASIS EURS' },
  FUN: { symbol: 'FUN', name: 'FunFair' },
  GNO: { symbol: 'GNO', name: 'Gnosis' },
  GNT: { symbol: 'GNT', name: 'Golem' },
  GUP: { symbol: 'GUP', name: 'Guppy' },
  GUSD: { symbol: 'GUSD', name: 'Gemini Dollar' },
  HMQ: { symbol: 'HMQ', name: 'Humaniq' },
  KNC: { symbol: 'KNC', name: 'Kyber Network' },
  LINK: { symbol: 'LINK', name: 'Link' },
  LUN: { symbol: 'LUN', name: 'Lunyr' },
  MANA: { symbol: 'MANA', name: 'Decentraland' },
  MCO: { symbol: 'MCO', name: 'Monaco' },
  MITH: { symbol: 'MITH', name: 'Mithril' },
  MKR: { symbol: 'MKR', name: 'Maker' },
  MLN: { symbol: 'MLN', name: 'Melon' },
  NEXO: { symbol: 'NEXO', name: 'NEXO' },
  NGC: { symbol: 'NGC', name: 'NAGA Coin' },
  NMR: { symbol: 'NMR', name: 'Numeraire' },
  NOAH: { symbol: 'NOAH', name: 'Noah' },
  OMG: { symbol: 'OMG', name: 'OmiseGo' },
  PAX: { symbol: 'PAX', name: 'Paxos Standard Token' },
  PAY: { symbol: 'PAY', name: 'TenXPay' },
  PMA: { symbol: 'PMA', name: 'PumaPay' },
  POLY: { symbol: 'POLY', name: 'Polymath' },
  POWR: { symbol: 'POWR', name: 'Power Ledger' },
  PPT: { symbol: 'PPT', name: 'Populous' },
  PTOY: { symbol: 'PTOY', name: 'Patientory' },
  R: { symbol: 'R', name: 'Revain' },
  RCN: { symbol: 'RCN', name: 'Ripio Credit Network' },
  REP: { symbol: 'REP', name: 'Augur' },
  RFR: { symbol: 'RFR', name: 'Refereum' },
  RLC: { symbol: 'RLC', name: 'iEx.ec' },
  SALT: { symbol: 'SALT', name: 'Salt' },
  SKIN: { symbol: 'SKIN', name: 'SkinCoin' },
  SNM: { symbol: 'SNM', name: 'SONM' },
  STORJ: { symbol: 'STORJ', name: 'Storj' },
  STORM: { symbol: 'STORM', name: 'Storm' },
  STX: { symbol: 'STX', name: 'Stox' },
  SWT: { symbol: 'SWT', name: 'Swarm City' },
  TEL: { symbol: 'TEL', name: 'Telcoin' },
  TRST: { symbol: 'TRST', name: 'Trustcoin' },
  TUSD: { symbol: 'TUSD', name: 'TrueUSD' },
  USDC: { symbol: 'USDC', name: 'USD coin' },
  VIB: { symbol: 'VIB', name: 'Viberate' },
  WAX: { symbol: 'WAX', name: 'WAX token' },
  WINGS: { symbol: 'WINGS', name: 'Wings DAO' },
  ZAP: { symbol: 'ZAP', name: 'Zap' },
  ZRX: { symbol: 'ZRX', name: '0x Protocol Token' },
  AION: { symbol: 'AION', name: 'Aion' },
  AMP: { symbol: 'AMP', name: 'Synereo' },
  ARK: { symbol: 'ARK', name: 'Ark' },
  BCD: { symbol: 'BCD', name: 'Bitcoin Diamond' },
  BCHABC: { symbol: 'BCHABC', name: 'Bitcoin Cash ABC' },
  BCHSV: { symbol: 'BCHSV', name: 'Bitcoin Cash SV' },
  BTC: { symbol: 'BTC', name: 'Bitcoin' },
  BTCP: { symbol: 'BTCP', name: 'Bitcoin Private' },
  BTG: { symbol: 'BTG', name: 'Bitcoin Gold' },
  DASH: { symbol: 'DASH', name: 'Dash' },
  DCR: { symbol: 'DCR', name: 'Decred' },
  DGB: { symbol: 'DGB', name: 'DigiByte' },
  DOGE: { symbol: 'DOGE', name: 'Dogecoin' },
  ETC: { symbol: 'ETC', name: 'Ethereum Classic' },
  EXP: { symbol: 'EXP', name: 'Expanse' },
  GRS: { symbol: 'GRS', name: 'Groestlcoin' },
  KMD: { symbol: 'KMD', name: 'Komodo' },
  LBC: { symbol: 'LBC', name: 'LBRY Credits' },
  LSK: { symbol: 'LSK', name: 'Lisk' },
  LTC: { symbol: 'LTC', name: 'Litecoin' },
  MAID: { symbol: 'MAID', name: 'MaidSafeCoin' },
  NAV: { symbol: 'NAV', name: 'NAV Coin' },
  NEO: { symbol: 'NEO', name: 'Neo' },
  NIM: { symbol: 'NIM', name: 'Nimiq' },
  NLG: { symbol: 'NLG', name: 'Gulden' },
  ONT: { symbol: 'ONT', name: 'Ontology' },
  PART: { symbol: 'PART', name: 'Particl' },
  POT: { symbol: 'POT', name: 'PotCoin' },
  PROC: { symbol: 'PROC', name: 'ProCurrency' },
  QTUM: { symbol: 'QTUM', name: 'Qtum Ignition' },
  SMART: { symbol: 'SMART', name: 'SmartCash' },
  STRAT: { symbol: 'STRAT', name: 'Stratis' },
  SYS: { symbol: 'SYS', name: 'Syscoin' },
  TRX: { symbol: 'TRX', name: 'Tron' },
  USDT: { symbol: 'USDT', name: 'Tether USD' },
  USNBT: { symbol: 'USNBT', name: 'NuBits' },
  WAVES: { symbol: 'WAVES', name: 'Waves' },
  XTZ: { symbol: 'XTZ', name: 'Tezos' },
  XVG: { symbol: 'XVG', name: 'Verge' },
  XZC: { symbol: 'XZC', name: 'ZCoin' },
  ZCL: { symbol: 'ZCL', name: 'Zclassic' },
  ZEC: { symbol: 'ZEC', name: 'Zcash' },
  ZEN: { symbol: 'ZEN', name: 'Horizen' }
};
export { ChangellyCurrencies };
