/**
 * Icon registry — the single source of truth for the v7 icon set (MEW-2359,
 * Design Library → 🗂️ Icons). AppIcon renders `icons[name][variant]`, so a name
 * only exists here if a glyph backs it and `IconName` catches typos at compile
 * time. Figma `style=stroke` maps to Heroicons `24/outline`, `style=filled` to
 * `24/solid`; the 9 glyphs Heroicons lacks are authored SFCs under ./custom.
 *
 * Per-icon named imports (no barrel) keep the bundle to the icons we register.
 * Sizes come from ICON_SIZES; the wrapper applies ICON_SIZE_CLASS. Color is
 * inherited via currentColor only — there is no color prop.
 */
import type { Component } from 'vue'

// Heroicons — style=stroke (Figma) → 24/outline
import {
  BookmarkIcon as BookmarkOutline,
  BookmarkSlashIcon as BookmarkSlashOutline,
  ClipboardDocumentIcon as ClipboardDocumentOutline,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckOutline,
  ChatBubbleBottomCenterIcon as ChatBubbleBottomCenterOutline,
  EnvelopeIcon as EnvelopeOutline,
  EnvelopeOpenIcon as EnvelopeOpenOutline,
  MegaphoneIcon as MegaphoneOutline,
  PaperAirplaneIcon as PaperAirplaneOutline,
  ShareIcon as ShareOutline,
  Cog6ToothIcon as Cog6ToothOutline,
  ComputerDesktopIcon as ComputerDesktopOutline,
  CpuChipIcon as CpuChipOutline,
  CursorArrowRaysIcon as CursorArrowRaysOutline,
  BanknotesIcon as BanknotesOutline,
  CreditCardIcon as CreditCardOutline,
  ReceiptPercentIcon as ReceiptPercentOutline,
  WalletIcon as WalletOutline,
  ChartBarIcon as ChartBarOutline,
  ChartPieIcon as ChartPieOutline,
  CircleStackIcon as CircleStackOutline,
  CubeIcon as CubeOutline,
  CubeTransparentIcon as CubeTransparentOutline,
  Squares2X2Icon as Squares2x2Outline,
  SquaresPlusIcon as SquaresPlusOutline,
  CalendarIcon as CalendarOutline,
  ClockIcon as ClockOutline,
  BeakerIcon as BeakerOutline,
  BugAntIcon as BugAntOutline,
  CloudIcon as CloudOutline,
  CloudArrowDownIcon as CloudArrowDownOutline,
  CloudArrowUpIcon as CloudArrowUpOutline,
  FireIcon as FireOutline,
  GlobeAltIcon as GlobeAltOutline,
  MoonIcon as MoonOutline,
  SunIcon as SunOutline,
  EyeIcon as EyeOutline,
  EyeSlashIcon as EyeSlashOutline,
  IdentificationIcon as IdentificationOutline,
  KeyIcon as KeyOutline,
  LockClosedIcon as LockClosedOutline,
  LockOpenIcon as LockOpenOutline,
  ShieldCheckIcon as ShieldCheckOutline,
  ShieldExclamationIcon as ShieldExclamationOutline,
  BellIcon as BellOutline,
  BellAlertIcon as BellAlertOutline,
  BellSlashIcon as BellSlashOutline,
  BellSnoozeIcon as BellSnoozeOutline,
  CheckBadgeIcon as CheckBadgeOutline,
  CheckCircleIcon as CheckCircleOutline,
  ExclamationCircleIcon as ExclamationCircleOutline,
  ExclamationTriangleIcon as ExclamationTriangleOutline,
  InformationCircleIcon as InformationCircleOutline,
  QuestionMarkCircleIcon as QuestionMarkCircleOutline,
  GiftIcon as GiftOutline,
  HeartIcon as HeartOutline,
  StarIcon as StarOutline,
  TrophyIcon as TrophyOutline,
  UserCircleIcon as UserCircleOutline,
  UserGroupIcon as UserGroupOutline,
  UserMinusIcon as UserMinusOutline,
  UserPlusIcon as UserPlusOutline,
  UsersIcon as UsersOutline,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalOutline,
  PencilIcon as PencilOutline,
  PencilSquareIcon as PencilSquareOutline,
  PuzzlePieceIcon as PuzzlePieceOutline,
  BoltIcon as BoltOutline,
  BoltSlashIcon as BoltSlashOutline,
  ViewfinderCircleIcon as ViewfinderCircleOutline,
  BackspaceIcon as BackspaceOutline,
  Bars2Icon as Bars2Outline,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircleOutline,
  FunnelIcon as FunnelOutline,
  LifebuoyIcon as LifebuoyOutline,
  TrashIcon as TrashOutline,
  XCircleIcon as XCircleOutline,
  AtSymbolIcon as AtSymbolOutline,
  DevicePhoneMobileIcon as DevicePhoneMobileOutline,
  DeviceTabletIcon as DeviceTabletOutline,
  QrCodeIcon as QrCodeOutline,
  PlusSmallIcon as PlusSmallOutline,
  CheckIcon as CheckOutline,
  EllipsisHorizontalIcon as EllipsisHorizontalOutline,
  EllipsisVerticalIcon as EllipsisVerticalOutline,
  Bars3Icon as Bars3Outline,
  BarsArrowDownIcon as BarsArrowDownOutline,
  BarsArrowUpIcon as BarsArrowUpOutline,
  DivideIcon as DivideOutline,
  EqualsIcon as EqualsOutline,
  CodeBracketIcon as CodeBracketOutline,
  ArrowDownIcon as ArrowDownOutline,
  ArrowDownCircleIcon as ArrowDownCircleOutline,
  ArrowDownLeftIcon as ArrowDownLeftOutline,
  ArrowDownOnSquareIcon as ArrowDownOnSquareOutline,
  ArrowDownOnSquareStackIcon as ArrowDownOnSquareStackOutline,
  ArrowDownRightIcon as ArrowDownRightOutline,
  ArrowDownTrayIcon as ArrowDownTrayOutline,
  ArrowLeftIcon as ArrowLeftOutline,
  ArrowLeftCircleIcon as ArrowLeftCircleOutline,
  ArrowLeftEndOnRectangleIcon as ArrowLeftEndOnRectangleOutline,
  ArrowLeftOnRectangleIcon as ArrowLeftOnRectangleOutline,
  ArrowLeftStartOnRectangleIcon as ArrowLeftStartOnRectangleOutline,
  ArrowLongDownIcon as ArrowLongDownOutline,
  ArrowLongLeftIcon as ArrowLongLeftOutline,
  ArrowLongRightIcon as ArrowLongRightOutline,
  ArrowLongUpIcon as ArrowLongUpOutline,
  ArrowPathIcon as ArrowPathOutline,
  ArrowPathRoundedSquareIcon as ArrowPathRoundedSquareOutline,
  ArrowRightIcon as ArrowRightOutline,
  ArrowRightCircleIcon as ArrowRightCircleOutline,
  ArrowRightEndOnRectangleIcon as ArrowRightEndOnRectangleOutline,
  ArrowRightOnRectangleIcon as ArrowRightOnRectangleOutline,
  ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangleOutline,
  ArrowSmallDownIcon as ArrowSmallDownOutline,
  ArrowSmallLeftIcon as ArrowSmallLeftOutline,
  ArrowSmallRightIcon as ArrowSmallRightOutline,
  ArrowSmallUpIcon as ArrowSmallUpOutline,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareOutline,
  ArrowTrendingDownIcon as ArrowTrendingDownOutline,
  ArrowTrendingUpIcon as ArrowTrendingUpOutline,
  ArrowUpIcon as ArrowUpOutline,
  ArrowUpCircleIcon as ArrowUpCircleOutline,
  ArrowUpLeftIcon as ArrowUpLeftOutline,
  ArrowUpOnSquareIcon as ArrowUpOnSquareOutline,
  ArrowUpOnSquareStackIcon as ArrowUpOnSquareStackOutline,
  ArrowUpRightIcon as ArrowUpRightOutline,
  ArrowUpTrayIcon as ArrowUpTrayOutline,
  ArrowUturnDownIcon as ArrowUturnDownOutline,
  ArrowUturnLeftIcon as ArrowUturnLeftOutline,
  ArrowUturnRightIcon as ArrowUturnRightOutline,
  ArrowUturnUpIcon as ArrowUturnUpOutline,
  ArrowsPointingInIcon as ArrowsPointingInOutline,
  ArrowsPointingOutIcon as ArrowsPointingOutOutline,
  ArrowsRightLeftIcon as ArrowsRightLeftOutline,
  ArrowsUpDownIcon as ArrowsUpDownOutline,
  ChevronDoubleDownIcon as ChevronDoubleDownOutline,
  ChevronDoubleLeftIcon as ChevronDoubleLeftOutline,
  ChevronDoubleRightIcon as ChevronDoubleRightOutline,
  ChevronDoubleUpIcon as ChevronDoubleUpOutline,
  ChevronDownIcon as ChevronDownOutline,
  ChevronLeftIcon as ChevronLeftOutline,
  ChevronRightIcon as ChevronRightOutline,
  ChevronUpIcon as ChevronUpOutline,
  ChevronUpDownIcon as ChevronUpDownOutline,
  PlusIcon as PlusOutline,
  XMarkIcon as XMarkOutline,
} from '@heroicons/vue/24/outline'

// Heroicons — style=filled (Figma) → 24/solid
import {
  BookmarkIcon as BookmarkSolid,
  BookmarkSlashIcon as BookmarkSlashSolid,
  ClipboardDocumentIcon as ClipboardDocumentSolid,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckSolid,
  ChatBubbleBottomCenterIcon as ChatBubbleBottomCenterSolid,
  EnvelopeIcon as EnvelopeSolid,
  EnvelopeOpenIcon as EnvelopeOpenSolid,
  MegaphoneIcon as MegaphoneSolid,
  PaperAirplaneIcon as PaperAirplaneSolid,
  ShareIcon as ShareSolid,
  Cog6ToothIcon as Cog6ToothSolid,
  ComputerDesktopIcon as ComputerDesktopSolid,
  CpuChipIcon as CpuChipSolid,
  CursorArrowRaysIcon as CursorArrowRaysSolid,
  BanknotesIcon as BanknotesSolid,
  CreditCardIcon as CreditCardSolid,
  ReceiptPercentIcon as ReceiptPercentSolid,
  WalletIcon as WalletSolid,
  ChartBarIcon as ChartBarSolid,
  ChartPieIcon as ChartPieSolid,
  CircleStackIcon as CircleStackSolid,
  CubeIcon as CubeSolid,
  CubeTransparentIcon as CubeTransparentSolid,
  Squares2X2Icon as Squares2x2Solid,
  SquaresPlusIcon as SquaresPlusSolid,
  CalendarIcon as CalendarSolid,
  ClockIcon as ClockSolid,
  BeakerIcon as BeakerSolid,
  BugAntIcon as BugAntSolid,
  CloudIcon as CloudSolid,
  CloudArrowDownIcon as CloudArrowDownSolid,
  CloudArrowUpIcon as CloudArrowUpSolid,
  FireIcon as FireSolid,
  GlobeAltIcon as GlobeAltSolid,
  MoonIcon as MoonSolid,
  SunIcon as SunSolid,
  EyeIcon as EyeSolid,
  EyeSlashIcon as EyeSlashSolid,
  IdentificationIcon as IdentificationSolid,
  KeyIcon as KeySolid,
  LockClosedIcon as LockClosedSolid,
  LockOpenIcon as LockOpenSolid,
  ShieldCheckIcon as ShieldCheckSolid,
  ShieldExclamationIcon as ShieldExclamationSolid,
  BellIcon as BellSolid,
  BellAlertIcon as BellAlertSolid,
  BellSlashIcon as BellSlashSolid,
  BellSnoozeIcon as BellSnoozeSolid,
  CheckBadgeIcon as CheckBadgeSolid,
  CheckCircleIcon as CheckCircleSolid,
  ExclamationCircleIcon as ExclamationCircleSolid,
  ExclamationTriangleIcon as ExclamationTriangleSolid,
  InformationCircleIcon as InformationCircleSolid,
  QuestionMarkCircleIcon as QuestionMarkCircleSolid,
  GiftIcon as GiftSolid,
  HeartIcon as HeartSolid,
  StarIcon as StarSolid,
  TrophyIcon as TrophySolid,
  UserCircleIcon as UserCircleSolid,
  UserGroupIcon as UserGroupSolid,
  UserMinusIcon as UserMinusSolid,
  UserPlusIcon as UserPlusSolid,
  UsersIcon as UsersSolid,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalSolid,
  PencilIcon as PencilSolid,
  PencilSquareIcon as PencilSquareSolid,
  PuzzlePieceIcon as PuzzlePieceSolid,
  BoltIcon as BoltSolid,
  BoltSlashIcon as BoltSlashSolid,
  ViewfinderCircleIcon as ViewfinderCircleSolid,
  BackspaceIcon as BackspaceSolid,
  Bars2Icon as Bars2Solid,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircleSolid,
  FunnelIcon as FunnelSolid,
  LifebuoyIcon as LifebuoySolid,
  TrashIcon as TrashSolid,
  XCircleIcon as XCircleSolid,
} from '@heroicons/vue/24/solid'

// Custom glyphs not in Heroicons — authored SFCs, currentColor, viewBox 24.
import CopyOutline from './custom/CopyOutline.vue'
import CopyFilled from './custom/CopyFilled.vue'
import CopiedOutline from './custom/CopiedOutline.vue'
import CopiedFilled from './custom/CopiedFilled.vue'
import BankOutline from './custom/BankOutline.vue'
import BankFilled from './custom/BankFilled.vue'
import ChartOutline from './custom/ChartOutline.vue'
import FaceIdOutline from './custom/FaceIdOutline.vue'
import RecoveryPhrase from './custom/RecoveryPhrase.vue'
import KeystoreOutline from './custom/KeystoreOutline.vue'
import KeystoreFilled from './custom/KeystoreFilled.vue'
import WatchOnlyOutline from './custom/WatchOnlyOutline.vue'
import PerpetualsFilled from './custom/PerpetualsFilled.vue'

/** Wrapper sizes (px). M/24 is the Figma authoring grid and the default. */
export const ICON_SIZES = {
  xxs: 16,
  xs: 18,
  s: 20,
  m: 24,
  l: 32,
  xl: 40,
  xxl: 56,
} as const

export type IconSize = keyof typeof ICON_SIZES

/** Tailwind size utility per wrapper size — `size-*` sets width + height. */
export const ICON_SIZE_CLASS: Record<IconSize, string> = {
  xxs: 'size-4',
  xs: 'size-[18px]',
  s: 'size-5',
  m: 'size-6',
  l: 'size-8',
  xl: 'size-10',
  xxl: 'size-14',
}

/** A glyph provides one or both variants; AppIcon falls back to the other. */
export type IconEntry = { stroke?: Component; filled?: Component }

export const icons = {
  bookmark: { stroke: BookmarkOutline, filled: BookmarkSolid },
  'bookmark-slash': {
    stroke: BookmarkSlashOutline,
    filled: BookmarkSlashSolid,
  },
  'clipboard-document': {
    stroke: ClipboardDocumentOutline,
    filled: ClipboardDocumentSolid,
  },
  'clipboard-document-check': {
    stroke: ClipboardDocumentCheckOutline,
    filled: ClipboardDocumentCheckSolid,
  },
  'chat-bubble-bottom-center': {
    stroke: ChatBubbleBottomCenterOutline,
    filled: ChatBubbleBottomCenterSolid,
  },
  envelope: { stroke: EnvelopeOutline, filled: EnvelopeSolid },
  'envelope-open': { stroke: EnvelopeOpenOutline, filled: EnvelopeOpenSolid },
  megaphone: { stroke: MegaphoneOutline, filled: MegaphoneSolid },
  'paper-airplane': {
    stroke: PaperAirplaneOutline,
    filled: PaperAirplaneSolid,
  },
  share: { stroke: ShareOutline, filled: ShareSolid },
  'cog-6-tooth': { stroke: Cog6ToothOutline, filled: Cog6ToothSolid },
  'computer-desktop': {
    stroke: ComputerDesktopOutline,
    filled: ComputerDesktopSolid,
  },
  'cpu-chip': { stroke: CpuChipOutline, filled: CpuChipSolid },
  'cursor-arrow-rays': {
    stroke: CursorArrowRaysOutline,
    filled: CursorArrowRaysSolid,
  },
  banknotes: { stroke: BanknotesOutline, filled: BanknotesSolid },
  'credit-card': { stroke: CreditCardOutline, filled: CreditCardSolid },
  'receipt-percent': {
    stroke: ReceiptPercentOutline,
    filled: ReceiptPercentSolid,
  },
  wallet: { stroke: WalletOutline, filled: WalletSolid },
  'chart-bar': { stroke: ChartBarOutline, filled: ChartBarSolid },
  'chart-pie': { stroke: ChartPieOutline, filled: ChartPieSolid },
  'circle-stack': { stroke: CircleStackOutline, filled: CircleStackSolid },
  cube: { stroke: CubeOutline, filled: CubeSolid },
  'cube-transparent': {
    stroke: CubeTransparentOutline,
    filled: CubeTransparentSolid,
  },
  'squares-2x2': { stroke: Squares2x2Outline, filled: Squares2x2Solid },
  'squares-plus': { stroke: SquaresPlusOutline, filled: SquaresPlusSolid },
  calendar: { stroke: CalendarOutline, filled: CalendarSolid },
  clock: { stroke: ClockOutline, filled: ClockSolid },
  beaker: { stroke: BeakerOutline, filled: BeakerSolid },
  'bug-ant': { stroke: BugAntOutline, filled: BugAntSolid },
  cloud: { stroke: CloudOutline, filled: CloudSolid },
  'cloud-arrow-down': {
    stroke: CloudArrowDownOutline,
    filled: CloudArrowDownSolid,
  },
  'cloud-arrow-up': { stroke: CloudArrowUpOutline, filled: CloudArrowUpSolid },
  fire: { stroke: FireOutline, filled: FireSolid },
  'globe-alt': { stroke: GlobeAltOutline, filled: GlobeAltSolid },
  moon: { stroke: MoonOutline, filled: MoonSolid },
  sun: { stroke: SunOutline, filled: SunSolid },
  eye: { stroke: EyeOutline, filled: EyeSolid },
  'eye-slash': { stroke: EyeSlashOutline, filled: EyeSlashSolid },
  identification: {
    stroke: IdentificationOutline,
    filled: IdentificationSolid,
  },
  key: { stroke: KeyOutline, filled: KeySolid },
  'lock-closed': { stroke: LockClosedOutline, filled: LockClosedSolid },
  'lock-open': { stroke: LockOpenOutline, filled: LockOpenSolid },
  'shield-check': { stroke: ShieldCheckOutline, filled: ShieldCheckSolid },
  'shield-exclamation': {
    stroke: ShieldExclamationOutline,
    filled: ShieldExclamationSolid,
  },
  bell: { stroke: BellOutline, filled: BellSolid },
  'bell-alert': { stroke: BellAlertOutline, filled: BellAlertSolid },
  'bell-slash': { stroke: BellSlashOutline, filled: BellSlashSolid },
  'bell-snooze': { stroke: BellSnoozeOutline, filled: BellSnoozeSolid },
  'check-badge': { stroke: CheckBadgeOutline, filled: CheckBadgeSolid },
  'check-circle': { stroke: CheckCircleOutline, filled: CheckCircleSolid },
  'exclamation-circle': {
    stroke: ExclamationCircleOutline,
    filled: ExclamationCircleSolid,
  },
  'exclamation-triangle': {
    stroke: ExclamationTriangleOutline,
    filled: ExclamationTriangleSolid,
  },
  'information-circle': {
    stroke: InformationCircleOutline,
    filled: InformationCircleSolid,
  },
  'question-mark-circle': {
    stroke: QuestionMarkCircleOutline,
    filled: QuestionMarkCircleSolid,
  },
  gift: { stroke: GiftOutline, filled: GiftSolid },
  heart: { stroke: HeartOutline, filled: HeartSolid },
  star: { stroke: StarOutline, filled: StarSolid },
  trophy: { stroke: TrophyOutline, filled: TrophySolid },
  'user-circle': { stroke: UserCircleOutline, filled: UserCircleSolid },
  'user-group': { stroke: UserGroupOutline, filled: UserGroupSolid },
  'user-minus': { stroke: UserMinusOutline, filled: UserMinusSolid },
  'user-plus': { stroke: UserPlusOutline, filled: UserPlusSolid },
  users: { stroke: UsersOutline, filled: UsersSolid },
  'adjustments-horizontal': {
    stroke: AdjustmentsHorizontalOutline,
    filled: AdjustmentsHorizontalSolid,
  },
  pencil: { stroke: PencilOutline, filled: PencilSolid },
  'pencil-square': { stroke: PencilSquareOutline, filled: PencilSquareSolid },
  'puzzle-piece': { stroke: PuzzlePieceOutline, filled: PuzzlePieceSolid },
  bolt: { stroke: BoltOutline, filled: BoltSolid },
  'bolt-slash': { stroke: BoltSlashOutline, filled: BoltSlashSolid },
  'viewfinder-circle': {
    stroke: ViewfinderCircleOutline,
    filled: ViewfinderCircleSolid,
  },
  backspace: { stroke: BackspaceOutline, filled: BackspaceSolid },
  'bars-2': { stroke: Bars2Outline, filled: Bars2Solid },
  'ellipsis-horizontal-circle': {
    stroke: EllipsisHorizontalCircleOutline,
    filled: EllipsisHorizontalCircleSolid,
  },
  funnel: { stroke: FunnelOutline, filled: FunnelSolid },
  lifebuoy: { stroke: LifebuoyOutline, filled: LifebuoySolid },
  trash: { stroke: TrashOutline, filled: TrashSolid },
  'x-circle': { stroke: XCircleOutline, filled: XCircleSolid },
  // --- stroke-only (Figma ships one variant) ---
  'at-symbol': { stroke: AtSymbolOutline },
  'device-phone-mobile': { stroke: DevicePhoneMobileOutline },
  'device-tablet': { stroke: DeviceTabletOutline },
  'qr-code': { stroke: QrCodeOutline },
  'plus-small': { stroke: PlusSmallOutline },
  check: { stroke: CheckOutline },
  'ellipsis-horizontal': { stroke: EllipsisHorizontalOutline },
  'ellipsis-vertical': { stroke: EllipsisVerticalOutline },
  'bars-3': { stroke: Bars3Outline },
  'bars-arrow-down': { stroke: BarsArrowDownOutline },
  'bars-arrow-up': { stroke: BarsArrowUpOutline },
  divide: { stroke: DivideOutline },
  equals: { stroke: EqualsOutline },
  'code-bracket': { stroke: CodeBracketOutline },
  'arrow-down': { stroke: ArrowDownOutline },
  'arrow-down-circle': { stroke: ArrowDownCircleOutline },
  'arrow-down-left': { stroke: ArrowDownLeftOutline },
  'arrow-down-on-square': { stroke: ArrowDownOnSquareOutline },
  'arrow-down-on-square-stack': { stroke: ArrowDownOnSquareStackOutline },
  'arrow-down-right': { stroke: ArrowDownRightOutline },
  'arrow-down-tray': { stroke: ArrowDownTrayOutline },
  'arrow-left': { stroke: ArrowLeftOutline },
  'arrow-left-circle': { stroke: ArrowLeftCircleOutline },
  'arrow-left-end-on-rectangle': { stroke: ArrowLeftEndOnRectangleOutline },
  'arrow-left-on-rectangle': { stroke: ArrowLeftOnRectangleOutline },
  'arrow-left-start-on-rectangle': { stroke: ArrowLeftStartOnRectangleOutline },
  'arrow-long-down': { stroke: ArrowLongDownOutline },
  'arrow-long-left': { stroke: ArrowLongLeftOutline },
  'arrow-long-right': { stroke: ArrowLongRightOutline },
  'arrow-long-up': { stroke: ArrowLongUpOutline },
  'arrow-path': { stroke: ArrowPathOutline },
  'arrow-path-rounded-square': { stroke: ArrowPathRoundedSquareOutline },
  'arrow-right': { stroke: ArrowRightOutline },
  'arrow-right-circle': { stroke: ArrowRightCircleOutline },
  'arrow-right-end-on-rectangle': { stroke: ArrowRightEndOnRectangleOutline },
  'arrow-right-on-rectangle': { stroke: ArrowRightOnRectangleOutline },
  'arrow-right-start-on-rectangle': {
    stroke: ArrowRightStartOnRectangleOutline,
  },
  'arrow-small-down': { stroke: ArrowSmallDownOutline },
  'arrow-small-left': { stroke: ArrowSmallLeftOutline },
  'arrow-small-right': { stroke: ArrowSmallRightOutline },
  'arrow-small-up': { stroke: ArrowSmallUpOutline },
  'arrow-top-right-on-square': { stroke: ArrowTopRightOnSquareOutline },
  'arrow-trending-down': { stroke: ArrowTrendingDownOutline },
  'arrow-trending-up': { stroke: ArrowTrendingUpOutline },
  'arrow-up': { stroke: ArrowUpOutline },
  'arrow-up-circle': { stroke: ArrowUpCircleOutline },
  'arrow-up-left': { stroke: ArrowUpLeftOutline },
  'arrow-up-on-square': { stroke: ArrowUpOnSquareOutline },
  'arrow-up-on-square-stack': { stroke: ArrowUpOnSquareStackOutline },
  'arrow-up-right': { stroke: ArrowUpRightOutline },
  'arrow-up-tray': { stroke: ArrowUpTrayOutline },
  'arrow-uturn-down': { stroke: ArrowUturnDownOutline },
  'arrow-uturn-left': { stroke: ArrowUturnLeftOutline },
  'arrow-uturn-right': { stroke: ArrowUturnRightOutline },
  'arrow-uturn-up': { stroke: ArrowUturnUpOutline },
  'arrows-pointing-in': { stroke: ArrowsPointingInOutline },
  'arrows-pointing-out': { stroke: ArrowsPointingOutOutline },
  'arrows-right-left': { stroke: ArrowsRightLeftOutline },
  'arrows-up-down': { stroke: ArrowsUpDownOutline },
  'chevron-double-down': { stroke: ChevronDoubleDownOutline },
  'chevron-double-left': { stroke: ChevronDoubleLeftOutline },
  'chevron-double-right': { stroke: ChevronDoubleRightOutline },
  'chevron-double-up': { stroke: ChevronDoubleUpOutline },
  'chevron-down': { stroke: ChevronDownOutline },
  'chevron-left': { stroke: ChevronLeftOutline },
  'chevron-right': { stroke: ChevronRightOutline },
  'chevron-up': { stroke: ChevronUpOutline },
  'chevron-up-down': { stroke: ChevronUpDownOutline },
  plus: { stroke: PlusOutline },
  'x-mark': { stroke: XMarkOutline },
  // --- custom glyphs (not in Heroicons; authored SFCs under ./custom) ---
  copy: { stroke: CopyOutline, filled: CopyFilled },
  copied: { stroke: CopiedOutline, filled: CopiedFilled },
  bank: { stroke: BankOutline, filled: BankFilled },
  chart: { stroke: ChartOutline },
  'face-id': { stroke: FaceIdOutline },
  'recovery-phrase': { stroke: RecoveryPhrase },
  keystore: { stroke: KeystoreOutline, filled: KeystoreFilled },
  'watch-only': { stroke: WatchOnlyOutline },
  perpetuals: { filled: PerpetualsFilled },
} as const satisfies Record<string, IconEntry>

export type IconName = keyof typeof icons

export const ICON_NAMES = Object.keys(icons) as IconName[]
