import flags from './flags';
class Currency {
  /**
   * @param {Object} currency
   * @param {string} currency.name - Curreny Name
   * @param {string} currency.value - Defaults to Curreny Name
   * @param {string} currency.img - Path to Icon
   */
  constructor({ name, value = name, img }) {
    this.name = name;
    this.value = value;
    this.img = img;
  }
}
/**
 * Returns array of Currency values with icons
 */
export default [
  /**
   * Unsorted currencies go here
   */
  new Currency({ name: 'USD', img: flags.usFlag }),
  ...[
    new Currency({ name: 'AED', img: flags.aeFlag }),
    new Currency({ name: 'AFN', img: flags.afFlag }),
    new Currency({ name: 'ALL', img: flags.alFlag }),
    new Currency({ name: 'AMD', img: flags.amFlag }),
    new Currency({ name: 'ANG', img: flags.agFlag }),
    new Currency({ name: 'AOA', img: flags.aoFlag }),
    new Currency({ name: 'ARS', img: flags.arFlag }),
    new Currency({ name: 'AUD', img: flags.auFlag }),
    new Currency({ name: 'AWG', img: flags.awFlag }),
    new Currency({ name: 'AZN', img: flags.azFlag }),
    new Currency({ name: 'BAM', img: flags.baFlag }),
    new Currency({ name: 'BBD', img: flags.bbFlag }),
    new Currency({ name: 'BDT', img: flags.bdFlag }),
    new Currency({ name: 'BGN', img: flags.bgFlag }),
    new Currency({ name: 'BHD', img: flags.bhFlag }),
    new Currency({ name: 'BIF', img: flags.biFlag }),
    new Currency({ name: 'BMD', img: flags.bmFlag }),
    new Currency({ name: 'BND', img: flags.bnFlag }),
    new Currency({ name: 'BOB', img: flags.boFlag }),
    new Currency({ name: 'BRL', img: flags.brFlag }),
    new Currency({ name: 'BSD', img: flags.bsFlag }),
    new Currency({ name: 'BTC', img: flags.btFlag }),
    new Currency({ name: 'BTN', img: flags.btFlag }),
    new Currency({ name: 'BWP', img: flags.bwFlag }),
    new Currency({ name: 'BYN', img: flags.byFlag }),
    new Currency({ name: 'BYR', img: flags }),
    new Currency({ name: 'BZD', img: flags }),
    new Currency({ name: 'CAD', img: flags }),
    new Currency({ name: 'CDF', img: flags }),
    new Currency({ name: 'CHF', img: flags }),
    new Currency({ name: 'CLF', img: flags }),
    new Currency({ name: 'CLP', img: flags }),
    new Currency({ name: 'CNY', img: flags }),
    new Currency({ name: 'COP', img: flags }),
    new Currency({ name: 'CRC', img: flags }),
    new Currency({ name: 'CUC', img: flags }),
    new Currency({ name: 'CUP', img: flags }),
    new Currency({ name: 'CVE', img: flags }),
    new Currency({ name: 'CZK', img: flags }),
    new Currency({ name: 'DJF', img: flags }),
    new Currency({ name: 'DKK', img: flags }),
    new Currency({ name: 'DOP', img: flags }),
    new Currency({ name: 'DZD', img: flags }),
    new Currency({ name: 'EGP', img: flags }),
    new Currency({ name: 'ERN', img: flags }),
    new Currency({ name: 'ETB', img: flags }),
    new Currency({ name: 'EUR', img: flags }),
    new Currency({ name: 'FJD', img: flags }),
    new Currency({ name: 'FKP', img: flags }),
    new Currency({ name: 'GBP', img: flags }),
    new Currency({ name: 'GEL', img: flags }),
    new Currency({ name: 'GGP', img: flags }),
    new Currency({ name: 'GHS', img: flags }),
    new Currency({ name: 'GIP', img: flags }),
    new Currency({ name: 'GMD', img: flags }),
    new Currency({ name: 'GNF', img: flags }),
    new Currency({ name: 'GTQ', img: flags }),
    new Currency({ name: 'GYD', img: flags }),
    new Currency({ name: 'HKD', img: flags }),
    new Currency({ name: 'HNL', img: flags }),
    new Currency({ name: 'HRK', img: flags }),
    new Currency({ name: 'HTG', img: flags }),
    new Currency({ name: 'HUF', img: flags }),
    new Currency({ name: 'IDR', img: flags }),
    new Currency({ name: 'ILS', img: flags }),
    new Currency({ name: 'IMP', img: flags }),
    new Currency({ name: 'INR', img: flags }),
    new Currency({ name: 'IQD', img: flags }),
    new Currency({ name: 'IRR', img: flags }),
    new Currency({ name: 'ISK', img: flags }),
    new Currency({ name: 'JEP', img: flags }),
    new Currency({ name: 'JMD', img: flags }),
    new Currency({ name: 'JOD', img: flags }),
    new Currency({ name: 'JPY', img: flags }),
    new Currency({ name: 'KES', img: flags }),
    new Currency({ name: 'KGS', img: flags }),
    new Currency({ name: 'KHR', img: flags }),
    new Currency({ name: 'KMF', img: flags }),
    new Currency({ name: 'KPW', img: flags }),
    new Currency({ name: 'KRW', img: flags }),
    new Currency({ name: 'KWD', img: flags }),
    new Currency({ name: 'KYD', img: flags }),
    new Currency({ name: 'KZT', img: flags }),
    new Currency({ name: 'LAK', img: flags }),
    new Currency({ name: 'LBP', img: flags }),
    new Currency({ name: 'LKR', img: flags }),
    new Currency({ name: 'LRD', img: flags }),
    new Currency({ name: 'LSL', img: flags }),
    new Currency({ name: 'LTL', img: flags }),
    new Currency({ name: 'LVL', img: flags }),
    new Currency({ name: 'LYD', img: flags }),
    new Currency({ name: 'MAD', img: flags }),
    new Currency({ name: 'MDL', img: flags }),
    new Currency({ name: 'MGA', img: flags }),
    new Currency({ name: 'MKD', img: flags }),
    new Currency({ name: 'MMK', img: flags }),
    new Currency({ name: 'MNT', img: flags }),
    new Currency({ name: 'MOP', img: flags }),
    new Currency({ name: 'MRO', img: flags }),
    new Currency({ name: 'MUR', img: flags }),
    new Currency({ name: 'MVR', img: flags }),
    new Currency({ name: 'MWK', img: flags }),
    new Currency({ name: 'MXN', img: flags }),
    new Currency({ name: 'MYR', img: flags }),
    new Currency({ name: 'MZN', img: flags }),
    new Currency({ name: 'NAD', img: flags }),
    new Currency({ name: 'NGN', img: flags }),
    new Currency({ name: 'NIO', img: flags }),
    new Currency({ name: 'NOK', img: flags }),
    new Currency({ name: 'NPR', img: flags }),
    new Currency({ name: 'NZD', img: flags }),
    new Currency({ name: 'OMR', img: flags }),
    new Currency({ name: 'PAB', img: flags }),
    new Currency({ name: 'PEN', img: flags }),
    new Currency({ name: 'PGK', img: flags }),
    new Currency({ name: 'PHP', img: flags }),
    new Currency({ name: 'PKR', img: flags }),
    new Currency({ name: 'PLN', img: flags }),
    new Currency({ name: 'PYG', img: flags }),
    new Currency({ name: 'QAR', img: flags }),
    new Currency({ name: 'RON', img: flags }),
    new Currency({ name: 'RSD', img: flags }),
    new Currency({ name: 'RUB', img: flags }),
    new Currency({ name: 'RWF', img: flags }),
    new Currency({ name: 'SAR', img: flags }),
    new Currency({ name: 'SBD', img: flags }),
    new Currency({ name: 'SCR', img: flags }),
    new Currency({ name: 'SDG', img: flags }),
    new Currency({ name: 'SEK', img: flags }),
    new Currency({ name: 'SGD', img: flags }),
    new Currency({ name: 'SHP', img: flags }),
    new Currency({ name: 'SLL', img: flags }),
    new Currency({ name: 'SOS', img: flags }),
    new Currency({ name: 'SRD', img: flags }),
    new Currency({ name: 'STD', img: flags }),
    new Currency({ name: 'SVC', img: flags }),
    new Currency({ name: 'SYP', img: flags }),
    new Currency({ name: 'SZL', img: flags }),
    new Currency({ name: 'THB', img: flags }),
    new Currency({ name: 'TJS', img: flags }),
    new Currency({ name: 'TMT', img: flags }),
    new Currency({ name: 'TND', img: flags }),
    new Currency({ name: 'TOP', img: flags }),
    new Currency({ name: 'TRY', img: flags }),
    new Currency({ name: 'TTD', img: flags }),
    new Currency({ name: 'TWD', img: flags }),
    new Currency({ name: 'TZS', img: flags }),
    new Currency({ name: 'UAH', img: flags }),
    new Currency({ name: 'UGX', img: flags }),
    new Currency({ name: 'USD', img: flags }),
    new Currency({ name: 'UYU', img: flags }),
    new Currency({ name: 'UZS', img: flags }),
    new Currency({ name: 'VEF', img: flags }),
    new Currency({ name: 'VND', img: flags }),
    new Currency({ name: 'VUV', img: flags }),
    new Currency({ name: 'WST', img: flags }),
    new Currency({ name: 'XAF', img: flags }),
    new Currency({ name: 'XAG', img: flags }),
    new Currency({ name: 'XAU', img: flags }),
    new Currency({ name: 'XCD', img: flags }),
    new Currency({ name: 'XDR', img: flags }),
    new Currency({ name: 'XOF', img: flags }),
    new Currency({ name: 'XPF', img: flags }),
    new Currency({ name: 'YER', img: flags }),
    new Currency({ name: 'ZAR', img: flags }),
    new Currency({ name: 'ZMK', img: flags }),
    new Currency({ name: 'ZMW', img: flags }),
    new Currency({ name: 'ZWL', img: flags })
  ].sort((a, b) => {
    if (a.name > b.name) return 1;
    if (a.name < b.name) return -1;
    return 0;
  })
];
