import Vue from 'vue';
const AppAddrQr = () => import('@/core/components/AppAddrQr.vue');
const AppQrCode = () => import('@/core/components/AppQrCode.vue');
const AppBlockTitle = () => import('@/core/components/AppBlockTitle.vue');
const AppBtnMenu = () => import('@/core/components/AppBtnMenu.vue');
const AppBtnRow = () => import('@/core/components/AppBtnRow.vue');
const AppButtonBalance = () => import('@/core/components/AppButtonBalance.vue');
const AppCopyBtn = () => import('@/core/components/AppCopyBtn.vue');
const AppModal = () => import('@/core/components/AppModal.vue');
const AppUserMsgBlock = () => import('@/core/components/AppUserMsgBlock.vue');
const BorderBlock = () => import('@/core/components/BorderBlock.vue');
const MewAddressSelect = () => import('@/core/components/MewAddressSelect.vue');
const MewAlert = () => import('@/core/components/MewAlert.vue');
const MewBadge = () => import('@/core/components/MewBadge.vue');
const MewBanner = () => import('@/core/components/MewBanner.vue');
const MewBlockie = () => import('@/core/components/MewBlockie.vue');
const MewButton = () => import('@/core/components/MewButton.vue');
const MewChart = () => import('@/core/components/MewChart.vue');
const MewCheckbox = () => import('@/core/components/MewCheckbox.vue');
const MewCopy = () => import('@/core/components/MewCopy.vue');
const MewDropdown = () => import('@/core/components/MewDropdown.vue');
const MewExpandPanel = () => import('@/core/components/MewExpandPanel.vue');
const MewInfoCard = () => import('@/core/components/MewInfoCard.vue');
const MewTooltip = () => import('@/core/components/MewTooltip.vue');
const MewIcon = () => import('@/core/components/MewIcon.vue');
const MewInput = () => import('@/core/components/MewInput.vue');
const MewIconButton = () => import('@/core/components/MewIconButton.vue');
const MewLightTable = () => import('@/core/components/MewLightTable.vue');
const MewMenu = () => import('@/core/components/MewMenu.vue');
const MewMenuPopup = () => import('@/core/components/MewMenuPopup.vue');
const MewModule = () => import('@/core/components/MewModule.vue');
const MewNotification = () => import('@/core/components/MewNotification.vue');
const MewOverlay = () => import('@/core/components/MewOverlay.vue');
const MewPopup = () => import('@/core/components/MewPopup.vue');
const MewProgressBar = () => import('@/core/components/MewProgressBar.vue');
const MewSearch = () => import('@/core/components/MewSearch.vue');
const MewSelect = () => import('@/core/components/MewSelect.vue');
const MewSheet = () => import('@/core/components/MewSheet.vue');
const MewStepper = () => import('@/core/components/MewStepper.vue');
const MewSuperButton = () => import('@/core/components/MewSuperButton.vue');
const MewSwitch = () => import('@/core/components/MewSwitch.vue');
const MewTable = () => import('@/core/components/MewTable.vue');
const MewTabs = () => import('@/core/components/MewTabs.vue');
const MewTextArea = () => import('@/core/components/MewTextArea.vue');
const MewToast = () => import('@/core/components/MewToast.vue');
const MewToggle = () => import('@/core/components/MewToggle.vue');
const MewTokenContainer = () =>
  import('@/core/components/MewTokenContainer.vue');
const MewTransformHash = () => import('@/core/components/MewTransformHash.vue');
const MewWarningSheet = () => import('@/core/components/MewWarningSheet.vue');
const WhiteSheet = () => import('@/core/components/WhiteSheet.vue');

Vue.component('AppAddrQr', AppAddrQr);
Vue.component('AppQrCode', AppQrCode);
Vue.component('AppBlockTitle', AppBlockTitle);
Vue.component('AppBtnMenu', AppBtnMenu);
Vue.component('AppBtnRow', AppBtnRow);
Vue.component('AppButtonBalance', AppButtonBalance);
Vue.component('AppCopyBtn', AppCopyBtn);
Vue.component('AppModal', AppModal);
Vue.component('AppUserMsgBlock', AppUserMsgBlock);
Vue.component('BorderBlock', BorderBlock);
Vue.component('MewAddressSelect', MewAddressSelect);
Vue.component('MewAlert', MewAlert);
Vue.component('MewBadge', MewBadge);
Vue.component('MewBanner', MewBanner);
Vue.component('MewBlockie', MewBlockie);
Vue.component('MewButton', MewButton);
Vue.component('MewChart', MewChart);
Vue.component('MewCheckbox', MewCheckbox);
Vue.component('MewCopy', MewCopy);
Vue.component('MewDropdown', MewDropdown);
Vue.component('MewExpandPanel', MewExpandPanel);
Vue.component('MewInfoCard', MewInfoCard);
Vue.component('MewTooltip', MewTooltip);
Vue.component('MewIcon', MewIcon);
Vue.component('MewInput', MewInput);
Vue.component('MewIconButton', MewIconButton);
Vue.component('MewLightTable', MewLightTable);
Vue.component('MewMenu', MewMenu);
Vue.component('MewMenuPopup', MewMenuPopup);
Vue.component('MewModule', MewModule);
Vue.component('MewNotification', MewNotification);
Vue.component('MewOverlay', MewOverlay);
Vue.component('MewPopup', MewPopup);
Vue.component('MewProgressBar', MewProgressBar);
Vue.component('MewSearch', MewSearch);
Vue.component('MewSelect', MewSelect);
Vue.component('MewSheet', MewSheet);
Vue.component('MewStepper', MewStepper);
Vue.component('MewSuperButton', MewSuperButton);
Vue.component('MewSwitch', MewSwitch);
Vue.component('MewTable', MewTable);
Vue.component('MewTabs', MewTabs);
Vue.component('MewTextArea', MewTextArea);
Vue.component('MewToast', MewToast);
Vue.component('MewToggle', MewToggle);
Vue.component('MewTokenContainer', MewTokenContainer);
Vue.component('MewTransformHash', MewTransformHash);
Vue.component('MewWarningSheet', MewWarningSheet);
Vue.component('WhiteSheet', WhiteSheet);
