import Vue from 'vue';
import Vuetify, {
  VApp,
  VBtn,
  VBtnToggle,
  VCard,
  VCardTitle,
  VCardSubtitle,
  VCardText,
  VCardActions,
  VCol,
  VContainer,
  VContent,
  VDialog,
  VDivider,
  VIcon,
  VImg,
  VList,
  VListItem,
  VListItemContent,
  VListItemIcon,
  VListItemTitle,
  VNavigationDrawer,
  VRow,
  VSheet,
  VBottomSheet,
  VToolbar,
  VTextField,
  VLayout,
  VSelect,
  VCombobox,
  VTooltip,
  VStepper,
  VStepperHeader,
  VStepperStep,
  VStepperItems,
  VStepperContent,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelContent,
  VExpansionPanelHeader,
  VSwitch,
  VCheckbox,
  VTab,
  VTabs,
  VTabsItems,
  VTabItem,
  VMenu,
  VMain,
  VSpacer,
  VSlider,
  VDataTable,
  VCarousel,
  VSlideXReverseTransition,
  VCarouselItem,
  VListGroup,
  VListItemGroup,
  VOverlay,
  VThemeProvider,
  VRadio,
  VRadioGroup
} from 'vuetify/lib';
import 'vuetify/dist/vuetify.min.css';

Vue.use(Vuetify, {
  components: {
    VApp,
    VBtn,
    VBtnToggle,
    VCard,
    VCardTitle,
    VCardSubtitle,
    VCardText,
    VCardActions,
    VCol,
    VContainer,
    VContent,
    VDialog,
    VDivider,
    VIcon,
    VImg,
    VList,
    VListItem,
    VListItemContent,
    VListItemIcon,
    VListItemTitle,
    VNavigationDrawer,
    VRow,
    VSheet,
    VBottomSheet,
    VToolbar,
    VTextField,
    VLayout,
    VSelect,
    VCombobox,
    VTooltip,
    VStepper,
    VStepperHeader,
    VStepperStep,
    VStepperItems,
    VStepperContent,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelContent,
    VExpansionPanelHeader,
    VSwitch,
    VCheckbox,
    VTab,
    VTabs,
    VTabsItems,
    VTabItem,
    VMenu,
    VMain,
    VSpacer,
    VSlider,
    VDataTable,
    VCarousel,
    VSlideXReverseTransition,
    VCarouselItem,
    VListGroup,
    VListItemGroup,
    VOverlay,
    VThemeProvider,
    VRadio,
    VRadioGroup
  }
});

export default new Vuetify({
  icons: {
    iconfont: 'mdi'
  },
  theme: {
    options: {
      customProperties: true
    },
    dark: false,
    themes: {
      light: {
        primaryHover: '#1eb19b',
        primaryActive: '#56c5b4',
        primaryOutlineActive: '#baede6',
        secondaryOutlineActive: '#d6dffa',
        errorOutlineActive: '#ffd7dc',
        basicOutlineActive: '#c5ccd3',
        selectActive: '#dcfff9',
        selectHover: '#f0f0f0',
        superPrimary: {
          base: '#f2fafa',
          darken1: '#e3f2f2'
        },
        superPrimaryHover: '#f5fdfb',
        overlayBg: '#f2fafa',
        inputBorder: '#e0e0e0',
        inputDisabled: '#cecece',
        dropdownBorder: '#05c0a5',
        progressBar: '#F3FAFA',
        txIn: '#7895f2',
        txOut: '#ffaf8f',
        swap: '#7fdefb',
        swapDisable: '#f8f8f8',
        captionPrimary: '#a9bcd2',
        textSecondary: '#999999',
        textSecondaryModule: '#999999',
        tagLabel: '#6d89a6',
        inputLabel: '#6d89a6',
        searchInput: '#f2f4fa',
        searchText: '#96a8b6',
        titlePrimary: '#0b2840',
        textPrimary: '#a3b7cf',
        textPrimaryModule: '#667f9b',
        white: '#fff',
        black: '#000',
        mewBg: '#fff',
        walletBg: '#f2f4fa',
        boxShadow: '#ececec',
        expandHeader: '#184f90',
        primary: '#05c0a5',
        secondary: '#5a78f0',
        basic: '#0b1a40',
        success: '#2cc479',
        error: {
          base: '#ff445b',
          lighten1: '#ffd7dc',
          lighten2: '#e96071'
        },
        warning: {
          base: '#FFF2DC',
          darken1: '#f5a623',
          darken2: '#ff7700'
        },
        disabled: '#cecece',
        tableHeader: '#f9f9f9'
      },
      dark: {
        primaryHover: '#1eb19b',
        primaryActive: '#56c5b4',
        primaryOutlineHover: '#03292c',
        primaryOutlineActive: '#15796a',
        secondaryOutlineHover: '#182040',
        secondaryOutlineActive: '#2e3c75',
        errorOutlineHover: '#361317',
        errorOutlineActive: '#651f28',
        basicOutlineHover: '#1e2a3e',
        basicOutlineActive: '#3d4e6b',
        selectActive: '#2e3c75',
        selectHover: '#2c3448',
        superPrimary: {
          base: '#242c48',
          darken1: '#e3f2f2'
        },
        superPrimaryHover: '#f5fdfb',
        overlayBg: '#151a29',
        inputBorder: '#667f9b',
        inputDisabled: '#3A465D',
        dropdownBorder: '#7e90a7',
        progressBar: '#151A29',
        txIn: '#7895f2',
        txOut: '#ffaf8f',
        swap: '#0f1320',
        swapDisable: '#0f1320',
        captionPrimary: '#a9bcd2',
        textSecondary: '#999999',
        inputLabel: '#4e5a6e',
        tagLabel: '#95aed8',
        searchInput: '#f2f4fa',
        searchText: '#96a8b6',
        white: '#fff',
        mewBg: '#151a29',
        walletBg: '#151a29',
        black: '#000',
        boxShadow: '#3c3c3c',
        expandHeader: '#184f90',
        titlePrimary: '#95aed8',
        textPrimary: '#4e5a6e',
        textPrimaryModule: '#95aed8',
        textSecondaryModule: '#95aed8',
        primary: '#05c0a5',
        secondary: '#5c79f0',
        basic: '#151A29',
        success: '#2cc479',
        error: {
          base: '#ff445b',
          lighten1: '#ffd7dc',
          lighten2: '#e96071'
        },
        warning: {
          base: '#FFF2DC',
          darken1: '#f5a623'
        },
        disabled: '#1f2b42',
        tableHeader: '#0f1320'
      }
    }
  }
});
