/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/addresses/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/addresses/{address}/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAddressEligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/addresses/{address}/rewards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAddressRewards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/addresses/{address}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAddressSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rewards/networks/{network}/orders/{orderHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimReward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rewards/orders/{orderHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReward"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rewards/pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRewardsPool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rewards/pool/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetailedRewardsPool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rewards/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/networks/{network}/orders/{orderHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RootInfo: {
            message: string;
        };
        Version: {
            name: string;
            version: string;
            commit: string;
            shortCommit: string;
            buildTime: string;
            branch: string;
            dirty: boolean;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            /**
             * Format: date-time
             * @description RFC 3339 timestamp. UTC unless a `tz` is requested
             */
            timestamp: string;
            /** @description Process uptime in seconds */
            uptime: number;
        };
        /**
         * @description Ethereum address, any casing. Normalised to lowercase by the server.
         * @example 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045
         */
        EthereumAddressInput: string;
        /**
         * @description Lowercase 0x prefixed Ethereum address.
         * @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045
         */
        EthereumAddress: string;
        AddressInfo: {
            id: null | number;
            address: components["schemas"]["EthereumAddress"];
        };
        /** @description Structured, endpoint-specific detail. Validation errors use an array of field errors. */
        ErrorDetail: {
            [key: string]: unknown;
        };
        Error: {
            error: {
                /** @description Stable machine-readable code, e.g. VALIDATION_FAILED, NOT_FOUND. */
                code: string;
                message: string;
                details: null | components["schemas"]["ErrorDetail"];
            };
        };
        /**
         * @description Why an address is not (yet) eligible.
         * @enum {string}
         */
        IneligibilityReason: "NO_BALANCE" | "BALANCE_TOO_LOW" | "NO_SNAPSHOTS" | "SYNCING" | "ALREADY_GRANTED" | "ALL_REWARDS_GRANTED" | "BLOCKLISTED" | "DEACTIVATED" | "ONLY_DEVS";
        Eligibility: {
            eligible: boolean;
            reasons: components["schemas"]["IneligibilityReason"][];
        };
        /**
         * Format: date-time
         * @description RFC 3339 timestamp.
         */
        TimestampInput: string;
        AddressRewardsCursorInput: {
            requestedAt: components["schemas"]["TimestampInput"];
        };
        /**
         * @description Lowercase 0x prefixed hash in hexadecimal format.
         * @example 0x3c9e05635969338b1c74e42f4701e3f7b7c6e13acecd2aecd1ee2f32da7287e2
         */
        Hash: string;
        /** @enum {string} */
        Network: "ETH" | "BSC";
        /** @enum {string} */
        RewardStatus: "REQUESTED" | "REJECTED" | "ERRORED" | "EXPIRED" | "APPROVED" | "PROCESSING" | "FAILED" | "REVOKED" | "REWARDED";
        /** @enum {string} */
        RewardTransactionStatus: "BROADCASTING" | "BROADCAST_FAILED" | "PENDING" | "DROPPED" | "REPLACED" | "PENDING_STUCK" | "MINED_SUCCESS" | "MINED_REVERTED";
        /** @enum {string} */
        FeeTier: "ECONOMY" | "REGULAR" | "FAST" | "FASTEST";
        RewardTransaction: {
            hash: components["schemas"]["Hash"];
            nonce: string;
            status: components["schemas"]["RewardTransactionStatus"];
            replacedBy: null | components["schemas"]["Hash"];
            /** Format: date-time */
            broadcastAt: string;
            feeTier: components["schemas"]["FeeTier"];
        };
        Reward: {
            orderHash: components["schemas"]["Hash"];
            network: components["schemas"]["Network"];
            status: components["schemas"]["RewardStatus"];
            recipientAddress: components["schemas"]["EthereumAddress"];
            /** Format: date-time */
            requestedAt: string;
            transactions: components["schemas"]["RewardTransaction"][];
        };
        AddressRewardCursor: {
            /** Format: date-time */
            requestedAt: string;
        };
        GetAddressRewardsResponse: {
            items: components["schemas"]["Reward"][];
            next: null | components["schemas"]["AddressRewardCursor"];
        };
        Snapshot: {
            date: string;
            /** @description Sum of all balances in USD */
            usdBalance: number;
        };
        /**
         * @description 1Inch order hash, any casing. Normalised to lowercase by the server.
         * @example 0x3c9e05635969338b1c74e42f4701e3f7b7c6e13acecd2aecd1ee2f32da7287e2
         */
        OrderHashInput: string;
        ClaimCreated: {
            message: string;
        };
        /** @enum {string} */
        ClaimFailReason: "ORDER_NOT_FOUND" | "ORDER_FUSION_4XX_ERROR" | "ORDER_FUSION_5XX_ERROR" | "ORDER_FUSION_UNKNOWN_ERROR" | "ORDER_INVALID_DATA" | "CONTRACT_METADATA_ERROR" | "REWARD_EXPIRED" | "MAKER_INELIGIBLE" | "SPEND_TOO_LOW" | "FAILED_ORDER_STATUS" | "UNKNOWN_ORDER_STATUS" | "REWARDS_DEACTIVATED";
        ClaimError: {
            error: {
                code: string;
                message: string;
                details: null | components["schemas"]["ErrorDetail"];
                reason: components["schemas"]["ClaimFailReason"];
            };
        };
        DeactivatedRewardPool: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DEACTIVATED";
            total: number;
            granted: number;
            remaining: number;
        };
        HoldAndTradeRewardPool: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HOLD_AND_TRADE";
            total: number;
            granted: number;
            remaining: number;
        };
        RewardsPool: components["schemas"]["DeactivatedRewardPool"] | components["schemas"]["HoldAndTradeRewardPool"];
        DetailedDeactivatedRewardPool: {
            /** @enum {string} */
            type: "DEACTIVATED";
            total: number;
            granted: number;
            remaining: number;
        };
        /** @enum {string} */
        RewardAsset: "USDC";
        DetailedHoldAndTradeRewardPoolNetwork: {
            network: components["schemas"]["Network"];
            address: components["schemas"]["EthereumAddress"];
            native: {
                symbol: string;
                decimals: number;
                balanceAtomic: string;
                balanceMain: string;
                balanceUsd: number;
                priceUsd: number;
                minFundedUsd: number;
                isFunded: boolean;
            };
            reward: {
                asset?: components["schemas"]["RewardAsset"];
                address: null | components["schemas"]["EthereumAddress"];
                symbol: string;
                decimals: number;
                balanceAtomic: string;
                balanceMain: string;
                balanceUsd: number;
                priceUsd: number;
                minMain: string;
                minFundedUsd: number;
                isFunded: boolean;
            };
        };
        DetailedHoldAndTradeRewardPool: {
            /** @enum {string} */
            type: "HOLD_AND_TRADE";
            total: number;
            granted: number;
            remaining: number;
            isFunded: boolean;
            networks: components["schemas"]["DetailedHoldAndTradeRewardPoolNetwork"][];
        };
        DetailedRewardsPool: components["schemas"]["DetailedDeactivatedRewardPool"] | components["schemas"]["DetailedHoldAndTradeRewardPool"];
        Deactivated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DEACTIVATED";
            /** Format: date-time */
            startedAt: string;
        };
        /** @enum {string} */
        RuleType: "DEACTIVATED" | "HOLD_AND_TRADE";
        HoldAndTrade: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HOLD_AND_TRADE";
            /** Format: date-time */
            startedAt: string;
            minMaintainedBalanceDurationMs: number;
            minMaintainedBalanceUsd: number;
            minTradeAmountUsd: number;
            rewardAsset: components["schemas"]["RewardAsset"];
            rewardAmountMain?: string;
        };
        Rule: components["schemas"]["Deactivated"] | components["schemas"]["HoldAndTrade"];
        Rules: {
            prev: null | components["schemas"]["Rule"];
            active: components["schemas"]["Rule"];
            next: null | components["schemas"]["Rule"];
        };
        OrderCounterparty: {
            contract: null | components["schemas"]["EthereumAddress"];
            decimals: number;
            amount: string;
            usdPrice: number;
            usdValue: number;
        };
    };
    responses: {
        /** @description Request failed validation (bad address format, bad query params). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Route or entity not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests. */
        RateLimited: {
            headers: {
                /** @description Seconds until requests may resume. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request conflicts with existing state (e.g. duplicate claim). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Claim failed to process. */
        ClaimFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ClaimError"];
            };
        };
    };
    parameters: {
        AddressPath: components["schemas"]["EthereumAddressInput"];
        AddressRewardsCursorQuery: components["schemas"]["AddressRewardsCursorInput"];
        LimitQuery: number;
        NetworkPath: components["schemas"]["Network"];
        OrderHashPath: components["schemas"]["OrderHashInput"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service description. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootInfo"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build and version info. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    getSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This OpenAPI document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: {
                /** @description IANA timezone name, e.g. Europe/Berlin */
                tz?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness check. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: components["parameters"]["AddressPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Address overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressInfo"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getAddressEligibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: components["parameters"]["AddressPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eligibility status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Eligibility"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getAddressRewards: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["AddressRewardsCursorQuery"];
                limit?: components["parameters"]["LimitQuery"];
            };
            header?: never;
            path: {
                address: components["parameters"]["AddressPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rewards for the address. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAddressRewardsResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getAddressSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: components["parameters"]["AddressPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance history for the address. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"][];
                };
            };
            400: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    claimReward: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network: components["parameters"]["NetworkPath"];
                orderHash: components["parameters"]["OrderHashPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claim result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimCreated"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ClaimFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    getReward: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderHash: components["parameters"]["OrderHashPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reward. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reward"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getRewardsPool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Global rewards pool state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardsPool"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getDetailedRewardsPool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Global rewards pool state detailed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedRewardsPool"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rewards rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rules"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network: components["parameters"]["NetworkPath"];
                orderHash: components["parameters"]["OrderHashPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 1inch Fusion Order Status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        from: components["schemas"]["OrderCounterparty"];
                        to: components["schemas"]["OrderCounterparty"];
                        orderStatus: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
}
