name: generate offline zip

on: [push]

jobs:
  offline-build:
    if: ${{contains(github.ref, 'offline')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup env
        run: |
          docker build -t mew-build-container .
          echo ::set-output name=NODE_VERSION::$(docker run --rm -v `pwd`:/home:rw mew-build-container /bin/bash -c "node --version")
        id: node-version
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{steps.node-version.outputs.NODE_VERSION}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{steps.node-version.outputs.NODE_VERSION}}-

      - name: npm install
        run: docker run --rm -v `pwd`:/home:rw --user "$(id -u):$(id -g)" mew-build-container /bin/bash -c "npm install"

      - name: build
        run: docker run --rm -v `pwd`:/home:rw mew-build-container /bin/bash -c "npm run build:offline"

      - name: generate zip for offline build
        if: contains(github.ref, 'offline')
        env:
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          GITHUB_TOKEN: ${{secrets.MEW_BOT_TOKEN}}
        run: |
          pip install --user awscli
          cd dist && zip -r ../OFFLINE-$GITHUB_SHA.zip * && cd ..
          aws s3 cp --acl public-read ./OFFLINE-$GITHUB_SHA.zip s3://mewbuilds/offline/OFFLINE-$GITHUB_SHA.zip
          curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST \
            -d "{\"body\": \"Copy of this zip can be found at <br/>https://www.mewbuilds.com/offline/OFFLINE-${GITHUB_SHA}.zip<br/> \"}" \
                            "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/comments"
